###
GET http://0.0.0.0:8080/accounts

###
POST localhost:8080/account
Content-Type: application/json
{"username": "ivan", "balance": 1000}

###
GET http://0.0.0.0:8080/account/f91f01a4-f68b-437f-9dc8-f97c4ef0baef

###
PUT http://0.0.0.0:8080/account
Content-Type: application/json
{"id": "f91f01a4-f68b-437f-9dc8-f97c4ef0baef", "username": "john"}

###
PUT http://0.0.0.0:8080/account/balance/plus
Content-Type: application/json
{"id": "9b193ade-5978-45d5-816d-529001635f7b", "balance": "10"}

###
PUT http://0.0.0.0:8080/account/balance/minus
Content-Type: application/json
{"id": "9b193ade-5978-45d5-816d-529001635f7b", "balance": "100"}

###
PUT http://0.0.0.0:8080/transaction
Content-Type: application/json
{"idSender": "f91f01a4-f68b-437f-9dc8-f97c4ef0baef", "idRecipient": "9b193ade-5978-45d5-816d-529001635f7b", "balanceChange": "500"}

###
DELETE http://0.0.0.0:8080/account/f91f01a4-f68b-437f-9dc8-f97c4ef0baef
