version: '3.8'

services:
  postgres:
    image: postgres:15.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "ivan"
      POSTGRES_PASSWORD: "password"
    volumes:
      - db:/var/lib/postgresql11/data
      - ./db/init-scripts.sql:/docker-entrypoint-initdb.d/scripts.sql

volumes:
  db:
    driver: local